name: bot deploy

on: [push, pull_request]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: SCP 
      uses: appleboy/scp-action@v0.0.5
      with: 
        username: root
        host: ${{ secrets.SERVER }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: "*.js, *.json"
        target: "roflBot"
